### ISSUE TITLE
[BUG] Handle warning messages

### ISSUE THREAD

**Issue by sdiazlor** [argilla-io/argilla-python#110]
1. If you search for a user/workspace that doesn't exists, it returns the model: `"User(id=None inserted_at=None updated_at=None username='username' role='annotator' first_name='username' last_name='username' password=None)"`. I would like to return a warning/error to know that.
2. When you delete a user/workspace, I would like to know which user/workspace I have deleted OR a message indicating that has been correctly deteled.
3. You can update dataset settings after adding records. In that case, only guidelines are updated. I would like a warning message.

```[tasklist]
### Tasks
- [x] Warning message non-existing user/workspace
- [x] Warning message user/workspace deletion
- [ ] Warning message update dataset settings with records
```
