### ISSUE TITLE
[feat]: Implement dataset creation features

### ISSUE THREAD

**Issue by burtenshaw** [argilla-io/argilla-python#15]
As part of the refactor project we need to be able to create datasets with the Argilla python SDK. This process consists of these steps:

- Defining the dataset's feedback task (fields, questions, settings, guidelines)
- Adding records to the dataset
- Deleting datasets

Each of the steps should function iteratively. I.e. a user should be able to re-define guidelines or append extra records. As highlighed https://github.com/argilla-io/argilla-python/pull/18#discussion_r1494428924 and a solution proposed [here](https://www.notion.so/argilla/Review-flow-working-with-Feedback-datasets-c4a8e97c55224c9796d901178012a216?pvs=4) 

> [!IMPORTANT]
> This issue is based on the interface designed in [this notebook](https://github.com/argilla-io/argilla-python/blob/develop/docs/_source/tutorials/end-to-end-argilla-tutorial.ipynb) . And uses the A,B,C line methodology, outlined there in. In short; A line is quick and easy, B line offer common configuration patterns, C line offers complete configuration.  
> Also, this process is subject to the ongoing UX interviews and community feedback sessions, so we should wait to receive more feedback and focus on the internal implementation as much as possible :hugs: .
 
# Defining the dataset's feedback task

The user needs to define a feedback task with fields and questions. 

**So far we have not decided on the workflow for this** and we have examples with `Template`, `Settings`, and a `Dataset` class that contains settings.

## A profile
The most abstracted profile may wish to define their feedback task based on their data's own structure. They could then iterate upon this once they've seen, either in the UI or SDK.

```python
dataset_list = [{"text": "Hello, world!"}, {"text": "I'm a sentence."}]
dataset = rg.Dataset.from_list(dataset_list, name="MyListDataset", field_keys=["text"])
```

## B Profile
Most users will want control over their task's representation.

```python
template = rg.Template(
    guidelines="Classify the articles into one of the four categories.",
    fields=[
        rg.Field(name="text", title="Text from the article"),
    ],
    questions=[
        rg.Question(
            name="label",
            title="In which category does this article fit?",
            required=True,
            settings=rg.QuestionSettings.MultiLabel(options=rg.LabelOption.from_labels(["greeting", "statement"])),
        )
    ],
)
```

## C Profile
Some users will want to update the feedback task representation:

```python
dataset = dataset.add_guidelines("how to use the dataset")
client.update(dataset)
```

# Adding records to the dataset

## A & B Profiles
Most users will be able to ingest records from a data structure and the SDK should match keys/collumn names to the template provided.  Raising errors for missing keys or mismatching arrays.

```python
dataset_list = [{"text": "Hello, world!"}, {"text": "I'm a sentence."}]
dataset_dict = {"text": ["Hello, world!", "I'm a sentence."]}
dataset_df = pd.DataFrame(dataset_dict)

# Adding records to the dataset
dataset = rg.Dataset.from_list(dataset_list, name="MyListDataset", field_keys=["text"])
# we raise an error if the dicts contain different keys
dataset = rg.Dataset.from_dict(dataset_dict, name="MyDictDataset", field_keys=["text"])
# we raise an error if the lists are different lengths
dataset = rg.Dataset.from_df(dataset_df, name="MyDfDataset", field_keys=["text"])
```

## C Profile

```python
dataset = rg.Dataset(name="MyListDataset", template=template)

# Adding records to the dataset
for i, item in enumerate(ds):
    dataset.records.add(
        rg.Record(
            fields={
                "text": item["text"],
            },
            external_id=f"record-{i}",
        )
    )
```

# Deleting datasets
```python
client.delete(dataset)
```

# Updating the dataset's settings/ template

Updating the dataset after its creation is a challenge in the current implementation of `FeedbackDatasets` as outlined [here](https://www.notion.so/argilla/Review-flow-working-with-Feedback-datasets-c4a8e97c55224c9796d901178012a216?pvs=4).

```python
settings = (
    DatasetSettings()
        .with_guidelines(path="path/to/guidelines.md")
        .with_text_field("prompt", use_markdown=True)
        .with_text_field("response", use_markdown=True)
        .with_label_question("sentiment",labels=["positive", "negative"])
        .with_text_question("comments", required=False)
)
```
> [!IMPORTANT]
> This strongly relates to the template and it may be confusing to have both.

## Functional requirements for updating after the dataset has been created

- The user should be able to change the guidelines 
- The user should be able to change field and question settings 
- The user should be able to append rows 

 

```[tasklist]
### Tasks
- [x] Answer: Should we define a dataset with Template/Settings object that is passed to a Dataset object, or should we define the settings in the Dataset and add_* to that dataset object to manipulate the settings.
- [x] Draft PR: How should we manage state between our Resource classes and ResourceModel pydantic models, such that they are robust and easy to build features off of.
- [ ] https://github.com/argilla-io/argilla-python/pull/25
```
