### ISSUE TITLE
docs: create quickstart and installation pages

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/argilla-python#58]
The idea is to create several installation pages focusing on 

```[tasklist]
### Tasks
- [x] quickstart: this page should rely on the based workflow outlined here https://github.com/argilla-io/argilla-python/pull/55. Additionally it should explain the [Hugging Face spaces docker deployment](https://docs.argilla.io/en/latest/getting_started/installation/deployments/huggingface-spaces.html).
- [x] installation/python-sdk: should showcase [the page we already](https://docs.argilla.io/en/latest/getting_started/installation/deployments/python.html) have without the extra requirements. Also, we can add a reference to the [developer install guide](https://docs.argilla.io/en/latest/community/developer_docs.html#development-setup).
- [x] ???? the remaining structure can be discussed with @burtenshaw and @jfcalvo to align with them what makes sense from a deployment/engineer perspective
```
