### ISSUE TITLE
docs: introduction, concepts, FAQ page

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/argilla-python#60]
```[tasklist]
### Tasks
- [ ] introduction: wrap up the introduction page and ensure the redirects are in order
- [ ] concepts/building blocks: to highlight the difference between `Datasets`, `settings` `Fields`, `Questions` etc.
- [ ] concepts/features: create a pragmatic and practical overview of features like [here](https://www.lilacml.com/)
- [ ] concepts/Components: create an overview of argilla components similar to the [dev documentation](https://docs.argilla.io/en/latest/community/developer_docs.html)
- [ ] [POTENTIALLY] concepts/best_practices_for_data: annotation guidelines, LLM data SFT vs preference tuning etc.
- [ ] [POTENTIALLY] FAQ: create a page for this
```

**Comment by nataliaElv** [comment]
@davidberenstein1957 @sdiazlor I see there's a branch linked to this issue. What's the best way to proceed in order to transfer this issue to `argilla`?

**Comment by sdiazlor** [comment]
@nataliaElv  I've just removed the branch, it was a remaining of the beginning of the project. Regarding the issue, I believe what remains is the discussion about how to present the introduction/components/concepts of argilla. So, maybe it's better to close this one and iterate over a new one?

**Comment by nataliaElv** [comment]
ok, closing it! Feel free to open a new issue with whatever is still left to do in the `argilla` repo.
