### ISSUE TITLE
docs: how to guides

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/argilla-python#61]
For the how to guides we already have [a general page](https://argilla-io.github.io/argilla-python/dev/how_to_guides/) This general page can be updated and changed. Potentially we can create sub-pages for each of the pages underneath but if possible, we can add the info in a single page.

Some things to keep in mind:
- These tutorials should be able to be followed from left to right, top to bottom.
- Clearly define the objective of the guide. What problem are you solving or what concept are you explaining? 
- Include code snippets to demonstrate implementation. These can be shown in tabs.
- Ideally, we should reference Python SDK definitions whenever possible.

```[tasklist]
### Tasks
- [ ] https://github.com/argilla-io/argilla-python/issues/87
- [ ] https://github.com/argilla-io/argilla-python/issues/93
- [ ] https://github.com/argilla-io/argilla-python/issues/94
- [ ] https://github.com/argilla-io/argilla-python/issues/95
- [ ] https://github.com/argilla-io/argilla-python/issues/186
- [ ] https://github.com/argilla-io/argilla-python/issues/187
- [ ] https://github.com/argilla-io/argilla-python/issues/188
```

**Comment by nataliaElv** [comment]
@sdiazlor would you say this issue is done and ready to close? I guess most of the work has been done already and if any other issues come up we can always open new issues that we can assign to the Argilla 2.0 milestone. What do you think?

**Comment by sdiazlor** [comment]
@nataliaElv Yes, I converted to individual issues the remaining tasks (so they can be assigned to a milestone as the SDK advances), and we can close this big one.

**Comment by nataliaElv** [comment]
Closing it then!
